language: minimal
sudo: required
before_install:
  - gpg2 --batch --passphrase '' --quick-gen-key test
  # https://podman.io/getting-started/installation#ubuntu
  - . /etc/os-release
  - sudo sh -c "echo 'deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list"
  - curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get -qq -y install podman
script:
  - podman run --rm -it antora/antora
